language: python

python:
  - 2.7

os:
  - osx

# command to install dependencies
install: "pip install -r requirements.txt"

# script
script:
  - make

# turn of notifications
notifications:
  email: false

